# SPDX-FileCopyrightText: (C) The Kokkos-FFT development team, see COPYRIGHT.md file
#
# SPDX-License-Identifier: MIT OR Apache-2.0 WITH LLVM-exception

[default.extend-words]
# Don't correct these word (parts)
iy = "iy"
ND = "ND"
SAV = "SAV"
arange = "arange"
