# SPDX-FileCopyrightText: (C) The kokkos-fft development team, see COPYRIGHT.md file
#
# SPDX-License-Identifier: MIT OR Apache-2.0 WITH LLVM-exception

# This job verifies the code formatting of C++ source files using the clang-format lint action.
# If any formatting inconsistencies are found compared to the expected style, the job will fail 
# and the differences will be displayed in the job log.
# See https://github.com/DoozyX/clang-format-lint-action for more details.

name: clang-format check

on:
  workflow_call:

permissions: read-all

jobs:
  clang-formatting-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3  # v6.0.0
    - uses: DoozyX/clang-format-lint-action@bcb4eb2cb0d707ee4f3e5cc3b456eb075f12cf73  # v0.20
      with:
        source: 'common/ fft/ examples/ install_test/ testing/ distributed/'
        exclude: ''
        extensions: 'hpp,cpp'
        clangFormatVersion: 17
